CREATE NONCLUSTERED INDEX IDX_ACT_HI_PROCINST_STARTTIME_PROCINST ON workflow.ACT_HI_PROCINST
(START_TIME_, PROC_INST_ID_);

CREATE NONCLUSTERED INDEX IDX_ACT_HI_VARINST_NAME_LONG ON workflow.ACT_HI_VARINST
(NAME_, LONG_);

CREATE NONCLUSTERED INDEX IDX_ACT_HI_VARINST_NAME_TEXT ON workflow.ACT_HI_VARINST
(NAME_, TEXT_);

CREATE NONCLUSTERED INDEX IDX_ACT_HI_VARINST_PROCINST_NAME_LONG ON workflow.ACT_HI_VARINST
(PROC_INST_ID_, NAME_, LONG_);

CREATE NONCLUSTERED INDEX IDX_ACT_HI_VARINST_PROCINST_NAME_TEXT ON workflow.ACT_HI_VARINST
(PROC_INST_ID_, NAME_, TEXT_);

CREATE NONCLUSTERED INDEX IDX_ACT_RU_TASK_PROCINST_TASKDEFKEY ON workflow.ACT_RU_TASK
(PROC_INST_ID_, TASK_DEF_KEY_);

CREATE NONCLUSTERED INDEX IDX_ACT_RU_VARIABLE_PROCINST_NAME_LONG ON workflow.ACT_RU_VARIABLE
(NAME_, PROC_INST_ID_, LONG_);